<a href="https://colab.research.google.com/github/rishicarter/Tensorflow_fundamentals/blob/main/00_Tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Importing Tensorflow
import tensorflow as tf
print(tf.__version__)

2.8.0


In [ ]:
# Check access to GPU
tf.config.list_physical_devices('GPU')

[]

In [ ]:
# Launch GPU
!nvidia-smi

NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.



In [ ]:
# Create tensors with tf.constant()
scalar=tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Check dimenensions
scalar.ndim

0

In [ ]:
vector = tf.constant([10, 10])
vector,vector.ndim

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>, 1)

In [ ]:
matrix = tf.constant([[10,7],[7,10]])
matrix,matrix.ndim

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 7, 10]], dtype=int32)>, 2)

In [ ]:
matrix = tf.constant([[10.,7.],[7.,10.],[1.,2.]], dtype=tf.float16)
matrix, matrix.ndim

(<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
 array([[10.,  7.],
        [ 7., 10.],
        [ 1.,  2.]], dtype=float16)>, 2)

In [ ]:
tensor = tf.constant([[[1,2,3],
                       [4,5,6]],[[7,8,9],
                                 [10,11,12]]])
tensor,tensor.ndim

(<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
 array([[[ 1,  2,  3],
         [ 4,  5,  6]],
 
        [[ 7,  8,  9],
         [10, 11, 12]]], dtype=int32)>, 3)

In [ ]:
# Create tesnors with tf.variable
tensor_var = tf.Variable([10,8])
tensor_var

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  8], dtype=int32)>

In [ ]:
# Random tensors
rand1 = tf.random.Generator.from_seed(42)
rand1 = rand1.normal(shape=(3,2))
rand1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [ ]:
rand2=tf.random.Generator.from_seed(42)
rand2=rand2.uniform(shape=(3,2))
rand2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.7493447 , 0.73561966],
       [0.45230794, 0.49039817],
       [0.1889317 , 0.52027524]], dtype=float32)>

In [ ]:
# shuffle
tensor = tf.constant([[10,7],
                      [3,4],
                      [2,5]])
tensor

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [ ]:
tf.random.set_seed(42)
tf.random.shuffle(tensor,seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [ ]:
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
tf.zeros(shape=(2,3,2))

<tf.Tensor: shape=(2, 3, 2), dtype=float32, numpy=
array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]], dtype=float32)>

In [ ]:
import numpy as np
numpy_A=np.arange(1,25,dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A = tf.constant(numpy_A)
B = tf.constant(numpy_A, shape=([4,3,2]))
A,B

(<tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>,
 <tf.Tensor: shape=(4, 3, 2), dtype=int32, numpy=
 array([[[ 1,  2],
         [ 3,  4],
         [ 5,  6]],
 
        [[ 7,  8],
         [ 9, 10],
         [11, 12]],
 
        [[13, 14],
         [15, 16],
         [17, 18]],
 
        [[19, 20],
         [21, 22],
         [23, 24]]], dtype=int32)>)

In [ ]:
rank4tensor = tf.zeros(shape=([2,3,4,5]))
rank4tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
def printstats(tensor):
  print('Datatype : ',tensor.dtype)
  print('nDims : ',tensor.ndim)
  print('Shape : ',tensor.shape)
  print('Element 0 axis : ',tensor.shape[0])
  print('Element last axis : ',tensor.shape[-1])
  print('Total elements in tensor : ',tf.size(tensor).numpy())
printstats(rank4tensor)

Datatype :  <dtype: 'float32'>
nDims :  4
Shape :  (2, 3, 4, 5)
Element 0 axis :  2
Element last axis :  5
Total elements in tensor :  120


In [ ]:
# indexing
rank4tensor[:1,:2,:2,:2]

<tf.Tensor: shape=(1, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
rank4tensor[:1,:,:2,:]

<tf.Tensor: shape=(1, 3, 2, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank2tensor = tf.constant([[10,7],[7,10]])
printstats(rank2tensor)

Datatype :  <dtype: 'int32'>
nDims :  2
Shape :  (2, 2)
Element 0 axis :  2
Element last axis :  2
Total elements in tensor :  4


In [ ]:
rank2tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [ ]:
rank3tensor = rank2tensor[...,tf.newaxis]
printstats(rank3tensor)

Datatype :  <dtype: 'int32'>
nDims :  3
Shape :  (2, 2, 1)
Element 0 axis :  2
Element last axis :  1
Total elements in tensor :  4


In [ ]:
'''
-1 => last
0 => first
1->n-1 => middle
'''
tf.expand_dims(rank2tensor,axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 7],
        [10]]], dtype=int32)>

In [ ]:
#Matrix Multiplication
tensor = tf.constant([[10,7],[7,10]])
tf.matmul(tensor,tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[149, 140],
       [140, 149]], dtype=int32)>

In [ ]:
tensor*tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [ 49, 100]], dtype=int32)>

In [ ]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
tensor@tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[149, 140],
       [140, 149]], dtype=int32)>

In [ ]:
X=tf.constant([[10,7],[7,10],[1,2]])
Y=tf.constant([[5,4,1],[2,3,8]])
X,Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 7, 10],
        [ 1,  2]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[5, 4, 1],
        [2, 3, 8]], dtype=int32)>)

In [ ]:
X@Y

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[64, 61, 66],
       [55, 58, 87],
       [ 9, 10, 17]], dtype=int32)>

In [ ]:
X_reshape = tf.reshape(X,shape=(2,3))
X@X_reshape

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[170,  77,  84],
       [170,  59,  69],
       [ 30,   9,  11]], dtype=int32)>

In [ ]:
Y_reshape=tf.reshape(Y,shape=(3,2))
Y@Y_reshape

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[32, 36],
       [37, 78]], dtype=int32)>

In [ ]:
X_transpose = tf.transpose(X)
X,X_transpose,X_reshape

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 7, 10],
        [ 1,  2]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[10,  7,  1],
        [ 7, 10,  2]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[10,  7,  7],
        [10,  1,  2]], dtype=int32)>)

In [ ]:
tf.tensordot(tf.transpose(X),Y_reshape,axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[60, 62],
       [51, 64]], dtype=int32)>

In [ ]:
# Changing datatype
B=tf.constant([1.7,4.4])
C=tf.constant([10,7])
B.dtype,C.dtype

(tf.float32, tf.int32)

In [ ]:
D=tf.cast(B,dtype=tf.float16)
B,D,D.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 4.4], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 4.4], dtype=float16)>,
 tf.float16)

In [ ]:
E=tf.cast(C,dtype=tf.float16)
C,E

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=float16, numpy=array([10.,  7.], dtype=float16)>)

In [ ]:
# Aggregation
## Get Absolute Values
tensor=tf.constant([-7,-10])
tensor,tf.abs(tensor)

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>)

In [ ]:
tensor=tf.constant(np.random.randint(0,100,size=50))
tf.reduce_min(tensor),tf.reduce_max(tensor),tf.reduce_sum(tensor),tf.reduce_mean(tensor)

(<tf.Tensor: shape=(), dtype=int64, numpy=0>,
 <tf.Tensor: shape=(), dtype=int64, numpy=98>,
 <tf.Tensor: shape=(), dtype=int64, numpy=2775>,
 <tf.Tensor: shape=(), dtype=int64, numpy=55>)

In [ ]:
tf.math.reduce_std(tf.cast(tensor,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=25.797869>

In [ ]:
# positional max and min
tf.random.set_seed(42)
tensor=tf.random.uniform(shape=[50])
tensor

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
tf.argmax(tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:
# index on largest value position
tensor[tf.argmax(tensor)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
tensor[tf.argmax(tensor)]==tf.reduce_max(tensor)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [ ]:
#tf.argmin(tensor),tensor[argmin(tensor)],tf.reduce_min(tensor)

In [ ]:
# Squeezing
tensor=tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,1,50))
tensor

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396,
           0.89256823, 0.94674826, 0.7493341 , 0.34925628, 0.54718256,
           0.26160395, 0.69734323, 0.11962581, 0.53484344, 0.7148968 ,
           0.87501776, 0.33967495, 0.17377627, 0.4418521 , 0.9008261 ,
           0.13803864, 0.12217975, 0.5754491 , 0.9417181 , 0.9186585 ,
           0.59708476, 0.6109482 , 0.82086265, 0.83269787, 0.8915849 ,
           0.01377225, 0.49807465, 0.57503664, 0.6856195 , 0.75972784,
           0.908944  , 0.40900218, 0.8765154 , 0.53890026, 0.42733097,
           0.401173  , 0.66623247, 0.16348064, 0.18220246, 0.97040176,
           0.06139731, 0.53034747, 0.9869994 , 0.4746945 , 0.8646754 ]]]]],
      dtype=float32)>

In [ ]:
tensor.shape

TensorShape([1, 1, 1, 1, 50])

In [ ]:
tensor_squeezed=tf.squeeze(tensor)
tensor_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396,
       0.89256823, 0.94674826, 0.7493341 , 0.34925628, 0.54718256,
       0.26160395, 0.69734323, 0.11962581, 0.53484344, 0.7148968 ,
       0.87501776, 0.33967495, 0.17377627, 0.4418521 , 0.9008261 ,
       0.13803864, 0.12217975, 0.5754491 , 0.9417181 , 0.9186585 ,
       0.59708476, 0.6109482 , 0.82086265, 0.83269787, 0.8915849 ,
       0.01377225, 0.49807465, 0.57503664, 0.6856195 , 0.75972784,
       0.908944  , 0.40900218, 0.8765154 , 0.53890026, 0.42733097,
       0.401173  , 0.66623247, 0.16348064, 0.18220246, 0.97040176,
       0.06139731, 0.53034747, 0.9869994 , 0.4746945 , 0.8646754 ],
      dtype=float32)>

In [ ]:
tensor_squeezed.shape

TensorShape([50])

In [ ]:
some_list = [0,1,2,3]
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
# custom one hot
tf.one_hot(some_list, depth=4, on_value='Hi', off_value='Bye')

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'Hi', b'Bye', b'Bye', b'Bye'],
       [b'Bye', b'Hi', b'Bye', b'Bye'],
       [b'Bye', b'Bye', b'Hi', b'Bye'],
       [b'Bye', b'Bye', b'Bye', b'Hi']], dtype=object)>

In [ ]:
tensor = tf.range(1,10)
tensor

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
tf.square(tensor)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
tf.sqrt(tf.cast(tensor,dtype=tf.float16))

<tf.Tensor: shape=(9,), dtype=float16, numpy=
array([1.   , 1.414, 1.732, 2.   , 2.236, 2.45 , 2.646, 2.828, 3.   ],
      dtype=float16)>

In [ ]:
tf.math.log(tf.cast(tensor,dtype=tf.float16))

<tf.Tensor: shape=(9,), dtype=float16, numpy=
array([0.    , 0.6934, 1.099 , 1.387 , 1.609 , 1.792 , 1.946 , 2.08  ,
       2.197 ], dtype=float16)>

In [ ]:
tensor = tf.constant(np.array([3.,7.,10.]))
tensor

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [ ]:
np.array(tensor)

array([ 3.,  7., 10.])